version: '3.8'
services:
  operations-service:
    build:
      context: .
      dockerfile: operations-service/Dockerfile
    image: operations-service:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "8123"
      CLICKHOUSE_USER: "admin"
      CLICKHOUSE_PASSWORD: "admin"
    depends_on:
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "8123:8123" # HTTP
      - "9000:9000" # native
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=admin
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  ch-ui:
    image: ghcr.io/caioricciuti/ch-ui:latest
    restart: always
    ports:
      - "5521:5521"
    environment:
      VITE_CLICKHOUSE_URL: "http://localhost:8123"
      VITE_CLICKHOUSE_USER: "admin"
      VITE_CLICKHOUSE_PASS: "admin"
      VITE_CLICKHOUSE_USE_ADVANCED: "false" 
      VITE_CLICKHOUSE_CUSTOM_PATH: ""
      VITE_CLICKHOUSE_REQUEST_TIMEOUT: "30000"
      VITE_BASE_PATH: "/"
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:
    driver: local
